# Generated by Django 4.1.3 on 2022-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
