# Generated by Django 4.1.3 on 2022-11-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_tarefa_data_alter_tarefa_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='horario',
            new_name='hora',
        ),
    ]
