# Generated by Django 4.1.3 on 2022-11-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_rename_hora_tarefa_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='horario',
            new_name='hora',
        ),
    ]
