# Generated by Django 4.1.3 on 2022-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cidade'),
        ),
    ]
