# Generated by Django 4.1.3 on 2022-11-27 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_customusuario_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='plano',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
